# Generated by Django 2.1 on 2018-09-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='PID',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='PID',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='FakeLeg',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
