# Generated by Django 2.1 on 2018-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20180930_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='UID',
            field=models.IntegerField(default=1),
        ),
    ]
