# Generated by Django 2.1 on 2018-09-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_guest_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='PID',
        ),
        migrations.AddField(
            model_name='date',
            name='RID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.Guest'),
        ),
    ]
