# Generated by Django 2.1 on 2018-09-30 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20180930_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='PID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.FakeLeg'),
        ),
    ]
