# Generated by Django 2.1 on 2018-10-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('booked_date', 'PID')},
        ),
    ]
