# Generated by Django 2.1 on 2018-10-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20181009_2049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('UID', 'start_date')},
        ),
    ]
